# Site settings
name: Dan Chavez
title: Dan Chavez | Full Stack Developer
description: Design-minded full stack developer who combines the power of code and design to bring ideas to life
url: https://www.dnachavez.com/
baseurl: ''
email: dna.chavez@outlook.com
cover: https://www.dnachavez.com/img/og.png
logo: https://www.dnachavez.com/img/emojis/technologist-medium-skin-tone.png
resume: https://www.dnachavez.com/dan-chavez-resume.pdf
social:
  - title: email
    url: mailto:dna.chavez@outlook.com
  - title: instagram
    url: https://instagram.com/dnachavez
  - title: github
    url: https://github.com/dnachavez

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
